# Generated by Django 4.0.1 on 2022-01-19 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumeroTrabajador', models.URLField(blank=True)),
                ('CURP', models.TextField(blank=True)),
                ('Direccion', models.TextField(blank=True)),
                ('Sueldo', models.CharField(blank=True, max_length=20)),
                ('Antiguedad', models.CharField(blank=True, max_length=20)),
                ('CorreoElectronico', models.CharField(blank=True, max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
