# Generated by Django 2.2.11 on 2020-12-02 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='position',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=100)),
                ('CURP', models.CharField(max_length=18)),
                ('sueldo', models.CharField(max_length=9)),
                ('mobile_no', models.CharField(max_length=10)),
                ('position', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='employeeregister.position')),
            ],
        ),
    ]
