# Generated by Django 4.0.1 on 2022-01-23 21:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeregister', '0002_alter_employee_id_alter_position_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pregunta1',
            field=models.CharField(default='novalue', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='pregunta2',
            field=models.CharField(default='novalue', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='pregunta3',
            field=models.CharField(default='novalue', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='pregunta4',
            field=models.CharField(default='novalue', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='pregunta5',
            field=models.CharField(default='novalue', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='pregunta6',
            field=models.CharField(default='novalue', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='CURP',
            field=models.CharField(max_length=18, validators=[django.core.validators.RegexValidator(
                '^([A-Z][AEIOUX][A-Z]{2}\\d{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\\d|3[01])[HM](?:AS|B[CS]|C[CLMSH]|D[FG]|G[TR]|HG|JC|M[CNS]|N[ETL]|OC|PL|Q[TR]|S[PLR]|T[CSL]|VZ|YN|ZS)[B-DF-HJ-NP-TV-Z]{3}[A-Z\\d])(\\d)$', message='Formato de CURP incorrecto')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='años_de_antiguedad',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(
                '^\\d{1,10}$', message='Solo numeros para indicar la ANTIGUEDAD')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nombre_completo',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(
                '^[a-zA-Z]{4,}(?: [a-zA-Z]+){0,2}$', message='Solo letras y al menos 4 letras para el NOMBRE COMPLETO')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='numero_de_empleado',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(
                '^\\d{1,10}$', message='Solo numeros para el NUMERO DE EMPLEADO')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sueldo',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(
                '^\\d{1,10}$', message='Solo numeros para el SUELDO')]),
        ),
    ]
