# Generated by Django 4.0.1 on 2022-01-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeregister', '0003_employee_pregunta1_employee_pregunta2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pregunta1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pregunta2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pregunta3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pregunta4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pregunta5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pregunta6',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
