# Generated by Django 4.0.1 on 2022-01-25 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeregister', '0004_alter_employee_pregunta1_alter_employee_pregunta2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='CURP',
            field=models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator('^([A-Z][AEIOUX][A-Z]{2}\\d{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\\d|3[01])[HM](?:AS|B[CS]|C[CLMSH]|D[FG]|G[TR]|HG|JC|M[CNS]|N[ETL]|OC|PL|Q[TR]|S[PLR]|T[CSL]|VZ|YN|ZS)[B-DF-HJ-NP-TV-Z]{3}[A-Z\\d])(\\d)$', message='Formato de CURP incorrecto')]),
        ),
    ]
