# Generated by Django 4.0.1 on 2022-01-25 21:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeregister', '0006_alter_employee_numero_de_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nombre_completo',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]{4,}(?: [a-zA-Z ]+){0,2}$', message='Solo letras y al menos 4 letras para el NOMBRE COMPLETO')]),
        ),
    ]
